### ISSUE TITLE
Expanding meta payload

### ISSUE THREAD

**Issue by andrewyatz** [ga4gh-discovery/service-info#1]
`/service-info` currently supports three attributes; `name`, `description` and `version`. We should use the spreadsheet of attributes to review what other items should go into this payload

**Comment by mcupak** [comment]
@andrewyatz Is there anything you'd want to add now besides what's already in or what's filed as an issue?

**Comment by mcupak** [comment]
Andy: good

**Comment by mcupak** [comment]
I reviewed the list one more time. I filed #21, I don't think we need to add anything else besides this and other already open issues.
