### ISSUE TITLE
Service info for implementations which support multiple APIs

### ISSUE THREAD

**Issue by andrewyatz** [ga4gh-discovery/service-info#22]
Brian from Cloud raised the idea that we could have a server, which implements multiple APIs. How can we support this idea? Feedback from cloud would be good as would anyone else.

Also cloud will go with a number of upcoming version changes with WES, DRS and TRS so it's a good time to get this scheduled in.

**Comment by jrambla** [comment]
So far, the service-info endpoint is associated with an URL or subdomain like beacon.myserver.com/service-info or myserver.com/beacon/service-info

 

Thus, my initial guess was that no collision would happen on servers hosting multiple APIs.

 

If the above does not match the use case, we can go for the REST apprpach of:

 

-          Myserver.com/services > returning a list of service-infos

-          Myserver.com/services/{service id}/ > returning an specific service-infos

 

 

Makes sense?

 

 

Jordi

**Comment by andrewyatz** [comment]
Miro suggested that this is in fact what the discovery service would do and
the solution might be to get the discovery service defined. So it’s not a
service info question

**Comment by andrewyatz** [comment]
We consider this to be out of scope and will be done by the discovery service. Confirmed on today's call
