### ISSUE TITLE
Name or type

### ISSUE THREAD

**Issue by andrewyatz** [ga4gh-discovery/service-info#3]
What is the purpose of name? Is this the same as a service type? What is the better word to describe this concept and its usage?

**Comment by Relequestual** [comment]
It wouldn't hurt to have a more detailed description and an example in the schema file.

**Comment by mcupak** [comment]
Good point. I think we should have both, I filed #8 to track type. I was thinking of the name as something like "PGP" vs. something like "DRS" for the type.

**Comment by mcupak** [comment]
+1 from Jordi and Andy
