### ISSUE TITLE
One or many versions supported by a single endpoint

### ISSUE THREAD

**Issue by andrewyatz** [ga4gh-discovery/service-info#4]
APIs can define only a single version. Is it possible for an API to declare that it supports multiple versions and if so how does it do this? Is this out of scope?

**Comment by mcupak** [comment]
I understand the refget use case, but I'm going to vote for out of scope in that most of the time such a situation would imply multiple services (or multiple versions of services).

**Comment by mcupak** [comment]
agreement to go with single
